// <auto-generated />
using MathApp.Backend.Data.Enteties;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MathApp.Migrations
{
    [DbContext(typeof(DataBase))]
    [Migration("20260213010513_MinorUpdatw")]
    partial class MinorUpdatw
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MathApp.Backend.Data.Enteties.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("MathApp.Backend.Data.Enteties.DefIncPair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DefinitionId")
                        .HasColumnType("int");

                    b.Property<int>("IncorrectDefinitionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DefinitionId");

                    b.HasIndex("IncorrectDefinitionId");

                    b.ToTable("DefIncPair");
                });

            modelBuilder.Entity("MathApp.Backend.Data.Enteties.Definition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Part1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Part2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("unitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("unitId");

                    b.ToTable("Definitions");
                });

            modelBuilder.Entity("MathApp.Backend.Data.Enteties.EducationLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("educationLevels");
                });

            modelBuilder.Entity("MathApp.Backend.Data.Enteties.IncorrectDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IncorrectDefinitions");
                });

            modelBuilder.Entity("MathApp.Backend.Data.Enteties.Pages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnitID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UnitID");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("MathApp.Backend.Data.Enteties.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("educationLevelId")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("educationLevelId");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("MathApp.Backend.Data.Enteties.UserProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<int>("all")
                        .HasColumnType("int");

                    b.Property<int>("good")
                        .HasColumnType("int");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("UnitId");

                    b.ToTable("UserProgresses");
                });

            modelBuilder.Entity("MathApp.Backend.Data.Enteties.DefIncPair", b =>
                {
                    b.HasOne("MathApp.Backend.Data.Enteties.Definition", null)
                        .WithMany("defIncPairs")
                        .HasForeignKey("DefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MathApp.Backend.Data.Enteties.IncorrectDefinition", null)
                        .WithMany("defIncPairs")
                        .HasForeignKey("IncorrectDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MathApp.Backend.Data.Enteties.Definition", b =>
                {
                    b.HasOne("MathApp.Backend.Data.Enteties.Unit", null)
                        .WithMany("definitions")
                        .HasForeignKey("unitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MathApp.Backend.Data.Enteties.Pages", b =>
                {
                    b.HasOne("MathApp.Backend.Data.Enteties.Unit", null)
                        .WithMany("pages")
                        .HasForeignKey("UnitID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MathApp.Backend.Data.Enteties.Unit", b =>
                {
                    b.HasOne("MathApp.Backend.Data.Enteties.EducationLevel", null)
                        .WithMany("Units")
                        .HasForeignKey("educationLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MathApp.Backend.Data.Enteties.UserProgress", b =>
                {
                    b.HasOne("MathApp.Backend.Data.Enteties.Account", null)
                        .WithMany("UserProgresses")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MathApp.Backend.Data.Enteties.Unit", null)
                        .WithMany("UserProgresses")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MathApp.Backend.Data.Enteties.Account", b =>
                {
                    b.Navigation("UserProgresses");
                });

            modelBuilder.Entity("MathApp.Backend.Data.Enteties.Definition", b =>
                {
                    b.Navigation("defIncPairs");
                });

            modelBuilder.Entity("MathApp.Backend.Data.Enteties.EducationLevel", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("MathApp.Backend.Data.Enteties.IncorrectDefinition", b =>
                {
                    b.Navigation("defIncPairs");
                });

            modelBuilder.Entity("MathApp.Backend.Data.Enteties.Unit", b =>
                {
                    b.Navigation("UserProgresses");

                    b.Navigation("definitions");

                    b.Navigation("pages");
                });
#pragma warning restore 612, 618
        }
    }
}
