// <auto-generated />
using System;
using MathApp.Backend.Data.Enteties;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MathApp.Migrations
{
    [DbContext(typeof(DataBase))]
    [Migration("20260104005254_IncDefs4")]
    partial class IncDefs4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Enteties.DefIncPair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DefinitionID")
                        .HasColumnType("int");

                    b.Property<int>("IncorrectID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DefIncPair");
                });

            modelBuilder.Entity("API.Enteties.IncorrectDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DefinitionId")
                        .HasColumnType("int");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DefinitionId");

                    b.ToTable("IncorrectDefinitions");
                });

            modelBuilder.Entity("MathApp.Enteties.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("MathApp.Enteties.Definition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Part1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Part2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("unitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("unitId");

                    b.ToTable("Definitions");
                });

            modelBuilder.Entity("MathApp.Enteties.EducationLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("educationLevels");
                });

            modelBuilder.Entity("MathApp.Enteties.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("educationLevelId")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("educationLevelId");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("API.Enteties.IncorrectDefinition", b =>
                {
                    b.HasOne("MathApp.Enteties.Definition", null)
                        .WithMany("IncorrectDefinitions")
                        .HasForeignKey("DefinitionId");
                });

            modelBuilder.Entity("MathApp.Enteties.Definition", b =>
                {
                    b.HasOne("MathApp.Enteties.Unit", null)
                        .WithMany("definitions")
                        .HasForeignKey("unitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MathApp.Enteties.Unit", b =>
                {
                    b.HasOne("MathApp.Enteties.EducationLevel", null)
                        .WithMany("Units")
                        .HasForeignKey("educationLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MathApp.Enteties.Definition", b =>
                {
                    b.Navigation("IncorrectDefinitions");
                });

            modelBuilder.Entity("MathApp.Enteties.EducationLevel", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("MathApp.Enteties.Unit", b =>
                {
                    b.Navigation("definitions");
                });
#pragma warning restore 612, 618
        }
    }
}
